export const HOME_ROUTE = "/"
export const DASHBOARD_ROUTE = "/dashboard"
export const NEW_PASSWORDD_ROUTE = "/reset-password"
export const FORGOT_PASSWORD_ROUTE = "/forgot-password"
export const PRIVACY_AND_POLICY_ROUTE = "/privacy-and-policy"
export const ABOUT_ROUTE = "/about"
export const PRODUCT_ROUTE = "/product"
